# Generated by Django 5.2.15 on 2026-06-17 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_service_catalog(apps, schema_editor):
    RegisteredService = apps.get_model('receipts', 'RegisteredService')
    ServiceCatalog = apps.get_model('receipts', 'ServiceCatalog')
    for service in RegisteredService.objects.all().order_by('name', 'id'):
        name = " ".join((service.name or "").strip().split()) or f"Service {service.pk}"
        catalog, _ = ServiceCatalog.objects.get_or_create(
            name=name,
            defaults={
                'billing_type': service.billing_type,
                'is_active': True,
                'memo': '',
            },
        )
        service.name = name
        service.catalog_service = catalog
        service.registration_source = service.registration_source or 'admin'
        service.save(update_fields=['name', 'catalog_service', 'registration_source'])


def unpopulate_service_catalog(apps, schema_editor):
    RegisteredService = apps.get_model('receipts', 'RegisteredService')
    RegisteredService.objects.update(catalog_service=None)


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredservice',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': '登録サービス', 'verbose_name_plural': '登録サービス'},
        ),
        migrations.AddField(
            model_name='registeredservice',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='停止日時'),
        ),
        migrations.AddField(
            model_name='registeredservice',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_registrations_deactivated', to=settings.AUTH_USER_MODEL, verbose_name='停止者'),
        ),
        migrations.AddField(
            model_name='registeredservice',
            name='deactivation_source',
            field=models.CharField(blank=True, choices=[('admin', '管理者停止'), ('user', 'ユーザー停止')], max_length=20, verbose_name='停止元'),
        ),
        migrations.AddField(
            model_name='registeredservice',
            name='final_receipt_month',
            field=models.DateField(blank=True, null=True, verbose_name='最後にアップロードすべき領収書月'),
        ),
        migrations.AddField(
            model_name='registeredservice',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_registrations_created', to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AddField(
            model_name='registeredservice',
            name='registration_source',
            field=models.CharField(choices=[('admin', '管理者登録'), ('user', 'ユーザー登録')], default='admin', max_length=20, verbose_name='登録元'),
        ),
        migrations.AddField(
            model_name='registeredservice',
            name='stop_note',
            field=models.TextField(blank=True, verbose_name='利用停止メモ'),
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='サービス名')),
                ('billing_type', models.CharField(choices=[('subscription', 'サブスク'), ('metered', '従量課金 / API'), ('one_time', '一回払い'), ('other', 'その他')], max_length=20, verbose_name='支払い種別')),
                ('is_active', models.BooleanField(default=True, verbose_name='選択可能')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_catalogs', to=settings.AUTH_USER_MODEL, verbose_name='作成管理者')),
            ],
            options={
                'verbose_name': 'サービスマスター',
                'verbose_name_plural': 'サービスマスター',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='registeredservice',
            name='catalog_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_services', to='receipts.servicecatalog', verbose_name='サービスマスター'),
        ),
        migrations.RunPython(populate_service_catalog, unpopulate_service_catalog),
    ]
