# Generated by Django 5.2.15 on 2026-06-17 04:48

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def normalize_service_name(value):
    return " ".join((value or "").strip().split())


def split_service_catalogs_by_billing_type(apps, schema_editor):
    """Ensure service masters are unique by service name + billing type.

    Version 0003 created one catalog per service name because service names were unique.
    If legacy user services used the same name with different billing types, this
    migration creates the missing catalog rows and reconnects each user service to
    the catalog with the matching billing type.
    """

    RegisteredService = apps.get_model("receipts", "RegisteredService")
    ServiceCatalog = apps.get_model("receipts", "ServiceCatalog")

    for service in RegisteredService.objects.select_related("catalog_service").all().order_by("id"):
        name = normalize_service_name(service.name) or f"Service {service.pk}"
        source_catalog = service.catalog_service
        matching_catalog = ServiceCatalog.objects.filter(name__iexact=name, billing_type=service.billing_type).order_by("id").first()
        if matching_catalog is None:
            matching_catalog = ServiceCatalog.objects.create(
                name=name,
                billing_type=service.billing_type,
                is_active=getattr(source_catalog, "is_active", True) if source_catalog else True,
                memo=getattr(source_catalog, "memo", "") if source_catalog else "",
                created_by_id=getattr(source_catalog, "created_by_id", None) if source_catalog else None,
            )
        if service.name != name or service.catalog_service_id != matching_catalog.pk:
            service.name = name
            service.catalog_service = matching_catalog
            service.save(update_fields=["name", "catalog_service"])

    canonical_by_key = {}
    for catalog in ServiceCatalog.objects.all().order_by("id"):
        name = normalize_service_name(catalog.name) or f"Service {catalog.pk}"
        key = (name.casefold(), catalog.billing_type)
        canonical = canonical_by_key.get(key)
        if canonical is None:
            canonical_by_key[key] = catalog
            updates = []
            if catalog.name != name:
                catalog.name = name
                updates.append("name")
            if updates:
                catalog.save(update_fields=updates + ["updated_at"])
            continue

        RegisteredService.objects.filter(catalog_service=catalog).update(catalog_service=canonical)
        if catalog.memo and not canonical.memo:
            canonical.memo = catalog.memo
            canonical.save(update_fields=["memo", "updated_at"])
        if catalog.is_active and not canonical.is_active:
            canonical.is_active = True
            canonical.save(update_fields=["is_active", "updated_at"])
        catalog.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_registeredservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredservice',
            options={'ordering': ['-is_active', 'name', 'billing_type'], 'verbose_name': '登録サービス', 'verbose_name_plural': '登録サービス'},
        ),
        migrations.AlterModelOptions(
            name='servicecatalog',
            options={'ordering': ['name', 'billing_type'], 'verbose_name': 'サービスマスター', 'verbose_name_plural': 'サービスマスター'},
        ),
        migrations.RemoveConstraint(
            model_name='registeredservice',
            name='unique_registered_service_per_user',
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='name',
            field=models.CharField(max_length=120, verbose_name='サービス名'),
        ),
        migrations.RunPython(split_service_catalogs_by_billing_type, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='registeredservice',
            constraint=models.UniqueConstraint(models.F('user'), django.db.models.functions.text.Lower('name'), models.F('billing_type'), name='unique_registered_service_per_user_name_billing_type_ci'),
        ),
        migrations.AddConstraint(
            model_name='servicecatalog',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('billing_type'), name='unique_service_catalog_name_billing_type_ci'),
        ),
    ]
