# Generated by Django 5.2.15 on 2026-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_alter_registeredservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ai_extracted_card_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='AI抽出カード下4桁'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_extracted_payee',
            field=models.CharField(blank=True, max_length=160, verbose_name='AI抽出払先'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_filename_admin_memo',
            field=models.TextField(blank=True, verbose_name='AIファイル名管理者メモ'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_filename_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AIファイル名確認日時'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_filename_status',
            field=models.CharField(choices=[('not_processed', '未確認'), ('generated', '作成済み'), ('needs_review', '要確認'), ('failed', '失敗'), ('skipped', 'スキップ')], default='not_processed', max_length=20, verbose_name='AIファイル名ステータス'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='generated_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='AI修正ファイル名'),
        ),
    ]
