# Generated by Django 5.2.15 on 2026-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_receipt_ai_extracted_card_last4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ai_period_check_memo',
            field=models.TextField(blank=True, verbose_name='AI提出月確認メモ'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_period_check_status',
            field=models.CharField(choices=[('not_checked', '未確認'), ('matched', '当月確認済み'), ('mismatched', '提出月不一致'), ('unknown', '確認不可')], default='not_checked', max_length=20, verbose_name='AI提出月確認ステータス'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_receipt_month',
            field=models.CharField(blank=True, max_length=7, verbose_name='AI判定領収書月'),
        ),
    ]
