# Generated by Django 5.2.15 on 2026-06-17 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_receipt_ai_period_check_memo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ai_check_amount',
            field=models.BooleanField(default=False, verbose_name='AI確認: 金額'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_check_card_last4',
            field=models.BooleanField(default=False, verbose_name='AI確認: カード末尾'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_check_currency',
            field=models.BooleanField(default=False, verbose_name='AI確認: 通貨'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_check_date',
            field=models.BooleanField(default=False, verbose_name='AI確認: 日付'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_check_payee',
            field=models.BooleanField(default=False, verbose_name='AI確認: 払先'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_check_period_match',
            field=models.BooleanField(default=False, verbose_name='AI確認: 提出月一致'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_check_service_payee_related',
            field=models.BooleanField(default=False, verbose_name='AI確認: サービス名と払先の関連性'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ai_service_payee_check_memo',
            field=models.TextField(blank=True, verbose_name='AIサービス名・払先確認メモ'),
        ),
        migrations.CreateModel(
            name='ReceiptResubmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(verbose_name='提出月')),
                ('service_name_snapshot', models.CharField(max_length=120, verbose_name='対象サービス名')),
                ('billing_type_snapshot', models.CharField(choices=[('subscription', 'サブスク'), ('metered', '従量課金 / API'), ('one_time', '一回払い'), ('other', 'その他')], max_length=20, verbose_name='対象支払い種別')),
                ('original_receipt_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='元領収書ID')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='元ファイル名')),
                ('display_filename', models.CharField(blank=True, max_length=255, verbose_name='表示ファイル名')),
                ('message', models.TextField(blank=True, verbose_name='ユーザー向けメッセージ')),
                ('status', models.CharField(choices=[('open', '再提出待ち'), ('resolved', '対応済み')], default='open', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='依頼日時')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='対応日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipt_resubmission_requests', to=settings.AUTH_USER_MODEL, verbose_name='依頼管理者')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_receipt_resubmission_requests', to=settings.AUTH_USER_MODEL, verbose_name='対応ユーザー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_resubmission_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '領収書再提出依頼',
                'verbose_name_plural': '領収書再提出依頼',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'period_month', 'status'], name='receipts_re_user_id_60f324_idx'), models.Index(fields=['service_name_snapshot', 'billing_type_snapshot'], name='receipts_re_service_a6c4e5_idx')],
            },
        ),
    ]
