# Generated by Django 5.2.15 on 2026-06-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_userprofile_tutorial_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='ai_filename_status',
            field=models.CharField(choices=[('not_processed', '未確認'), ('queued', 'AI待機中'), ('processing', 'AI抽出中'), ('generated', '作成済み'), ('needs_review', '要確認'), ('failed', '失敗'), ('skipped', 'スキップ')], default='not_processed', max_length=20, verbose_name='AIファイル名ステータス'),
        ),
    ]
