# Generated by Django 5.2.15 on 2026-06-18 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0010_rebuild_ai_generated_filenames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('reminder_initial', '4日リマインダー'), ('reminder_urgent', '10日重要リマインダー'), ('test', 'テスト送信')], max_length=40, verbose_name='メール種別')),
                ('target_month', models.DateField(blank=True, null=True, verbose_name='対象提出月')),
                ('to_email', models.EmailField(max_length=254, verbose_name='送信先')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('status', models.CharField(choices=[('sent', '送信済み'), ('failed', '失敗'), ('skipped', 'スキップ')], default='sent', max_length=20, verbose_name='ステータス')),
                ('message', models.TextField(blank=True, verbose_name='本文')),
                ('error', models.TextField(blank=True, verbose_name='エラー')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='重複防止キー')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipt_email_logs', to=settings.AUTH_USER_MODEL, verbose_name='実行管理者')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_email_logs', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
            ],
            options={
                'verbose_name': 'メール送信ログ',
                'verbose_name_plural': 'メール送信ログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_type', 'target_month', 'status'], name='receipts_em_email_t_20bb62_idx'), models.Index(fields=['to_email', 'created_at'], name='receipts_em_to_emai_ef886a_idx')],
            },
        ),
    ]
