# Generated by Django 5.2.15 on 2026-06-18 15:27

from django.db import migrations, models


ACTIVE = "active"
STOPPED = "stopped"


def sync_existing_user_statuses(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("receipts", "UserProfile")
    RegisteredService = apps.get_model("receipts", "RegisteredService")

    for user in User.objects.filter(is_staff=False, is_superuser=False):
        has_active_service = RegisteredService.objects.filter(user_id=user.pk, is_active=True).exists()
        status = ACTIVE if has_active_service else STOPPED
        profile, created = UserProfile.objects.get_or_create(user_id=user.pk, defaults={"account_status": status})
        if not created and profile.account_status != status:
            profile.account_status = status
            profile.save(update_fields=["account_status"])


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0011_email_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_status',
            field=models.CharField(choices=[('active', '利用中'), ('stopped', '停止中')], default='stopped', max_length=20, verbose_name='利用ステータス'),
        ),
        migrations.RunPython(sync_existing_user_statuses, migrations.RunPython.noop),
    ]
