# Generated by Django 5.2.15 on 2026-06-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_user_account_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildeliverylog',
            name='email_type',
            field=models.CharField(choices=[('reminder_initial', '通常リマインダー'), ('reminder_urgent', '重要リマインダー'), ('test', 'テスト送信')], max_length=40, verbose_name='メール種別'),
        ),
        migrations.CreateModel(
            name='EmailReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_day', models.PositiveSmallIntegerField(default=4, verbose_name='リマインダー日')),
                ('warning_day', models.PositiveSmallIntegerField(default=10, verbose_name='警告日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_email_reminder_schedules', to=settings.AUTH_USER_MODEL, verbose_name='更新管理者')),
            ],
            options={
                'verbose_name': 'メールリマインダー日設定',
                'verbose_name_plural': 'メールリマインダー日設定',
            },
        ),
    ]
