# Generated by Django 5.2.16 on 2026-07-12 05:37

import django.core.validators
import django.db.models.deletion
import receipts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0013_alter_emaildeliverylog_email_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreminderschedule',
            name='initial_body_template',
            field=models.TextField(default='{user_name} 様\n\nまだ領収書をアップロードしていない方にお送りします。\n{target_month}分について、以下のサービスの領収書をアップロードしてください。\n\n{missing_services}\n\nアップロードページ: {upload_url}\n\nアップロード後は、対象月の領収書が揃っていることを確認して「提出する」を押してください。\n\n{app_name}', verbose_name='通常リマインダー本文'),
        ),
        migrations.AddField(
            model_name='emailreminderschedule',
            name='initial_subject_template',
            field=models.CharField(default='{app_name}: {target_month}分の領収書アップロードをお願いします', max_length=255, verbose_name='通常リマインダー件名'),
        ),
        migrations.AddField(
            model_name='emailreminderschedule',
            name='urgent_body_template',
            field=models.TextField(default='{user_name} 様\n\nまだ領収書をアップロードしていない方にお送りします。\n{target_month}分の確認が完了していません。本日中にご対応ください。\n\n未アップロードのサービス:\n{missing_services}\n\n従量課金 / APIの利用確認が必要なサービス:\n{api_pending_services}\n\nAPIサービスを利用していない場合は、アップロードページで「今月は利用なし」を選択してください。\n\nアップロードページ: {upload_url}\n\n{app_name}', verbose_name='重要リマインダー本文'),
        ),
        migrations.AddField(
            model_name='emailreminderschedule',
            name='urgent_subject_template',
            field=models.CharField(default='【重要】{app_name}: {target_month}分の領収書を本日中にアップロードしてください', max_length=255, verbose_name='重要リマインダー件名'),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='merchant_aliases',
            field=models.TextField(blank=True, help_text='例: OPENAI *CHATGPT, OPENAI.COM。カンマまたは改行で複数指定できます。', verbose_name='カード明細・払先の表記候補'),
        ),
        migrations.CreateModel(
            name='CardStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(verbose_name='対象月')),
                ('file', models.FileField(upload_to=receipts.models.statement_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp']), receipts.models.validate_upload_size], verbose_name='ご利用代金明細書')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='元ファイル名')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='ファイルサイズ')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Content-Type')),
                ('status', models.CharField(choices=[('processing', 'AI解析中'), ('completed', '解析済み'), ('needs_review', '要確認'), ('failed', '解析失敗')], default='processing', max_length=20, verbose_name='解析ステータス')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='カード下4桁')),
                ('statement_period', models.CharField(blank=True, max_length=7, verbose_name='AI判定対象月')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='支払日')),
                ('ai_admin_memo', models.TextField(blank=True, verbose_name='AI管理者メモ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析完了日時')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ファイル保存期限')),
                ('file_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='ファイル削除日時')),
                ('file_delete_reason', models.CharField(blank=True, max_length=40, verbose_name='ファイル削除理由')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_card_statements', to=settings.AUTH_USER_MODEL, verbose_name='アップロード管理者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ご利用代金明細書',
                'verbose_name_plural': 'ご利用代金明細書',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CardStatementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('line_reference', models.CharField(blank=True, max_length=40, verbose_name='明細番号')),
                ('transaction_date', models.DateField(blank=True, null=True, verbose_name='利用日')),
                ('merchant_name', models.CharField(max_length=255, verbose_name='ご利用先')),
                ('merchant_normalized', models.CharField(blank=True, max_length=255, verbose_name='正規化ご利用先')),
                ('amount_jpy', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='請求金額（円）')),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='外貨金額')),
                ('original_currency', models.CharField(blank=True, max_length=3, verbose_name='外貨通貨')),
                ('match_status', models.CharField(choices=[('matched', 'サービス一致'), ('ambiguous', '曖昧'), ('unmatched', '未一致'), ('ignored', '対象外')], default='unmatched', max_length=20, verbose_name='一致ステータス')),
                ('match_confidence', models.FloatField(default=0, verbose_name='一致信頼度')),
                ('match_memo', models.TextField(blank=True, verbose_name='確認メモ')),
                ('receipt_required', models.BooleanField(default=False, verbose_name='領収書が必要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('matched_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_items', to='receipts.receipt', verbose_name='一致領収書')),
                ('matched_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_items', to='receipts.registeredservice', verbose_name='一致サービス')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.cardstatement')),
            ],
            options={
                'verbose_name': 'カード明細項目',
                'verbose_name_plural': 'カード明細項目',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyServiceDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(verbose_name='対象月')),
                ('no_usage', models.BooleanField(default=True, verbose_name='当月利用なし')),
                ('note', models.TextField(blank=True, verbose_name='補足')),
                ('declared_at', models.DateTimeField(auto_now_add=True, verbose_name='申告日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_usage_declarations_created', to=settings.AUTH_USER_MODEL, verbose_name='申告者')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_declarations', to='receipts.registeredservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_service_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '月次サービス利用申告',
                'verbose_name_plural': '月次サービス利用申告',
                'ordering': ['-period_month', 'service__name'],
            },
        ),
        migrations.AddIndex(
            model_name='cardstatement',
            index=models.Index(fields=['user', 'period_month', 'status'], name='receipts_ca_user_id_d14dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='cardstatementitem',
            index=models.Index(fields=['statement', 'match_status', 'receipt_required'], name='receipts_ca_stateme_c731e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyservicedeclaration',
            constraint=models.UniqueConstraint(fields=('user', 'service', 'period_month'), name='unique_monthly_service_declaration'),
        ),
    ]
