# Generated by Django 5.2.16 on 2026-07-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0014_emailreminderschedule_initial_body_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_extra',
            field=models.BooleanField(default=False, help_text='返金・プラン変更など、登録サービスに紐づかない『その他』の領収書です。', verbose_name='登録外の追加領収書'),
        ),
        migrations.AddField(
            model_name='receiptresubmissionrequest',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='登録外の追加領収書'),
        ),
        migrations.AddField(
            model_name='receiptresubmissionrequest',
            name='receipt_memo_snapshot',
            field=models.TextField(blank=True, verbose_name='領収書メモ'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='receipts.registeredservice', verbose_name='登録サービス'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_extra', True), ('service__isnull', True)), models.Q(('is_extra', False), ('service__isnull', False)), _connector='OR'), name='receipt_extra_service_consistency'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('is_extra', False), models.Q(('memo', ''), _negated=True), _connector='OR'), name='receipt_extra_memo_required'),
        ),
    ]
