# Generated by Django 5.2.16 on 2026-07-12 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_global_statement_links(apps, schema_editor):
    CardStatementItem = apps.get_model('receipts', 'CardStatementItem')
    for item in CardStatementItem.objects.select_related(
        'statement__user',
        'matched_service__user',
        'matched_service__catalog_service',
        'matched_receipt__submission__user',
        'matched_receipt__service__catalog_service',
    ).iterator():
        matched_user_id = None
        matched_catalog_id = None
        if item.matched_receipt_id:
            matched_user_id = item.matched_receipt.submission.user_id
            if item.matched_receipt.service_id:
                matched_catalog_id = item.matched_receipt.service.catalog_service_id
        if item.matched_service_id:
            matched_user_id = matched_user_id or item.matched_service.user_id
            matched_catalog_id = matched_catalog_id or item.matched_service.catalog_service_id
        if matched_user_id is None and item.statement_id:
            matched_user_id = item.statement.user_id
        CardStatementItem.objects.filter(pk=item.pk).update(
            matched_user_id=matched_user_id,
            matched_catalog_service_id=matched_catalog_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0015_extra_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cardstatement',
            name='receipts_ca_user_id_d14dc3_idx',
        ),
        migrations.AddField(
            model_name='cardstatement',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='領収書照合日時'),
        ),
        migrations.AddField(
            model_name='cardstatementitem',
            name='matched_catalog_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_items', to='receipts.servicecatalog', verbose_name='一致サービスマスター'),
        ),
        migrations.AddField(
            model_name='cardstatementitem',
            name='matched_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_items', to=settings.AUTH_USER_MODEL, verbose_name='一致ユーザー'),
        ),
        migrations.RunPython(populate_global_statement_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='cardstatement',
            name='user',
        ),
        migrations.AddIndex(
            model_name='cardstatement',
            index=models.Index(fields=['period_month', 'status'], name='receipts_ca_period__90912a_idx'),
        ),
    ]
