# Generated by Django 5.2.16 on 2026-07-13 14:43

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0016_global_card_statements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredservice',
            name='registration_source',
            field=models.CharField(choices=[('admin', '管理者登録'), ('user', 'ユーザー登録'), ('exception_request', '例外申請承認')], default='admin', max_length=20, verbose_name='登録元'),
        ),
        migrations.CreateModel(
            name='ServiceExceptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=120, verbose_name='サービス名')),
                ('billing_type', models.CharField(choices=[('subscription', 'サブスク'), ('metered', '従量課金 / API'), ('one_time', '一回払い'), ('other', 'その他')], max_length=20, verbose_name='支払い方法')),
                ('purpose', models.TextField(verbose_name='用途')),
                ('status', models.CharField(choices=[('pending', '確認待ち'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='ステータス')),
                ('review_note', models.TextField(blank=True, verbose_name='管理者コメント')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('approved_catalog_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exception_requests', to='receipts.servicecatalog', verbose_name='承認後サービスマスター')),
                ('approved_registered_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exception_requests', to='receipts.registeredservice', verbose_name='承認後利用サービス')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_exception_requests', to=settings.AUTH_USER_MODEL, verbose_name='確認管理者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_exception_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請ユーザー')),
            ],
            options={
                'verbose_name': 'サービス例外申請',
                'verbose_name_plural': 'サービス例外申請',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='receipts_se_status_270c6a_idx'), models.Index(fields=['user', 'status'], name='receipts_se_user_id_334727_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('service_name'), models.F('user'), models.F('billing_type'), condition=models.Q(('status', 'pending')), name='unique_pending_service_exception_request_ci')],
            },
        ),
    ]
