# Generated by Django 5.2.16 on 2026-07-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_receipt_upload_actor(apps, schema_editor):
    Receipt = apps.get_model("receipts", "Receipt")
    queryset = Receipt.objects.select_related("submission").filter(uploaded_by__isnull=True)
    for receipt in queryset.iterator(chunk_size=500):
        receipt.upload_source = "user"
        receipt.uploaded_by_id = receipt.submission.user_id
        receipt.save(update_fields=["upload_source", "uploaded_by"])


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0017_alter_registeredservice_registration_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="upload_source",
            field=models.CharField(
                choices=[("user", "ユーザー本人"), ("admin", "管理者代理")],
                default="user",
                max_length=20,
                verbose_name="アップロード元",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="アップロード実行者",
            ),
        ),
        migrations.RunPython(backfill_receipt_upload_actor, migrations.RunPython.noop),
    ]
