# Generated by Django 5.2.16 on 2026-07-20 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0018_receipt_upload_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='admin_filename_overridden',
            field=models.BooleanField(default=False, verbose_name='管理者によるファイル名修正'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='admin_review_note',
            field=models.TextField(blank=True, verbose_name='管理者確認メモ'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='admin_review_status',
            field=models.CharField(choices=[('not_reviewed', '未確認'), ('confirmed', '管理者確認済み')], default='not_reviewed', max_length=20, verbose_name='管理者確認ステータス'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='管理者確認日時'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipts', to=settings.AUTH_USER_MODEL, verbose_name='確認管理者'),
        ),
    ]
