# Generated by Django 5.2.16 on 2026-07-21 03:36

from datetime import date

from django.db import migrations, models


OLD_INITIAL_SUBJECT = "{app_name}: {target_month}分の領収書アップロードをお願いします"
OLD_INITIAL_BODY = """{user_name} 様

まだ領収書をアップロードしていない方にお送りします。
{target_month}分について、以下のサービスの領収書をアップロードしてください。

{missing_services}

アップロードページ: {upload_url}

アップロード後は、対象月の領収書が揃っていることを確認して「提出する」を押してください。

{app_name}"""
OLD_URGENT_SUBJECT = "【重要】{app_name}: {target_month}分の領収書を本日中にアップロードしてください"
OLD_URGENT_BODY = """{user_name} 様

まだ領収書をアップロードしていない方にお送りします。
{target_month}分の確認が完了していません。本日中にご対応ください。

未アップロードのサービス:
{missing_services}

従量課金 / APIの利用確認が必要なサービス:
{api_pending_services}

APIサービスを利用していない場合は、アップロードページで「今月は利用なし」を選択してください。

アップロードページ: {upload_url}

{app_name}"""

NEW_INITIAL_SUBJECT = "{app_name}: {receipt_month}分の領収書アップロードをお願いします"
NEW_INITIAL_BODY = """{user_name} 様

まだ領収書をアップロードしていない方にお送りします。
提出月 {target_month} の対象となる {receipt_month}分について、以下のサービスの領収書をアップロードしてください。

{missing_services}

アップロードページ: {upload_url}

アップロード後は、対象領収書月の領収書が揃っていることを確認して「提出する」を押してください。

{app_name}"""
NEW_URGENT_SUBJECT = "【重要】{app_name}: {receipt_month}分の領収書を本日中にアップロードしてください"
NEW_URGENT_BODY = """{user_name} 様

まだ領収書をアップロードしていない方にお送りします。
提出月 {target_month} の対象となる {receipt_month}分の確認が完了していません。本日中にご対応ください。

未アップロードのサービス:
{missing_services}

従量課金 / APIの利用確認が必要なサービス:
{api_pending_services}

APIサービスを利用していない場合は、アップロードページで「対象領収書月は利用なし」を選択してください。

アップロードページ: {upload_url}

{app_name}"""


def _month_start(value):
    return value.replace(day=1)


def _previous_month(value):
    value = _month_start(value)
    if value.month == 1:
        return date(value.year - 1, 12, 1)
    return date(value.year, value.month - 1, 1)


def _parse_month(value):
    value = (value or "").strip()
    try:
        return date.fromisoformat(f"{value}-01") if len(value) == 7 else None
    except ValueError:
        return None


def apply_submission_receipt_month_semantics(apps, schema_editor):
    Receipt = apps.get_model("receipts", "Receipt")
    EmailReminderSchedule = apps.get_model("receipts", "EmailReminderSchedule")

    # 管理者が編集したテンプレートは維持し、旧初期値のままの項目だけ新しい月表現へ更新する。
    EmailReminderSchedule.objects.filter(initial_subject_template=OLD_INITIAL_SUBJECT).update(
        initial_subject_template=NEW_INITIAL_SUBJECT
    )
    EmailReminderSchedule.objects.filter(initial_body_template=OLD_INITIAL_BODY).update(
        initial_body_template=NEW_INITIAL_BODY
    )
    EmailReminderSchedule.objects.filter(urgent_subject_template=OLD_URGENT_SUBJECT).update(
        urgent_subject_template=NEW_URGENT_SUBJECT
    )
    EmailReminderSchedule.objects.filter(urgent_body_template=OLD_URGENT_BODY).update(
        urgent_body_template=NEW_URGENT_BODY
    )

    # 既存ファイルのAI月判定を「提出月の前月」という正しいルールで再計算する。
    # 物理ファイルを削除済みのレコードは復元できないため、残っている領収書だけを補正する。
    queryset = Receipt.objects.select_related("submission").exclude(submission__period_month__isnull=True)
    for receipt in queryset.iterator(chunk_size=500):
        actual_month = _month_start(receipt.issued_on) if receipt.issued_on else _parse_month(receipt.ai_receipt_month)
        if actual_month is None:
            continue
        expected_month = _previous_month(receipt.submission.period_month)
        matched = actual_month == expected_month
        receipt.ai_receipt_month = actual_month.strftime("%Y-%m")
        receipt.ai_check_period_match = matched
        receipt.ai_period_check_status = "matched" if matched else "mismatched"
        if matched:
            receipt.ai_period_check_memo = (
                f"領収書日付の月 {actual_month:%Y-%m} は、提出月 {receipt.submission.period_month:%Y-%m} の "
                f"対象領収書月 {expected_month:%Y-%m} と一致しています。"
            )
        else:
            receipt.ai_period_check_memo = (
                f"領収書日付の月 {actual_month:%Y-%m} は、提出月 {receipt.submission.period_month:%Y-%m} の "
                f"対象領収書月 {expected_month:%Y-%m} と一致しません。管理者による確認が必要です。"
            )
            if receipt.admin_review_status == "confirmed":
                receipt.admin_review_status = "not_reviewed"
                receipt.admin_reviewed_by_id = None
                receipt.admin_reviewed_at = None
        receipt.save(
            update_fields=[
                "ai_receipt_month",
                "ai_check_period_match",
                "ai_period_check_status",
                "ai_period_check_memo",
                "admin_review_status",
                "admin_reviewed_by",
                "admin_reviewed_at",
            ]
        )


def reverse_submission_receipt_month_semantics(apps, schema_editor):
    # 業務ルールのデータ補正は安全に元へ戻せないため、逆移行では何もしない。
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0019_receipt_admin_filename_overridden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstatement',
            name='period_month',
            field=models.DateField(verbose_name='領収書月'),
        ),
        migrations.AlterField(
            model_name='cardstatement',
            name='statement_period',
            field=models.CharField(blank=True, max_length=7, verbose_name='AI判定領収書月'),
        ),
        migrations.AlterField(
            model_name='emailreminderschedule',
            name='initial_body_template',
            field=models.TextField(default='{user_name} 様\n\nまだ領収書をアップロードしていない方にお送りします。\n提出月 {target_month} の対象となる {receipt_month}分について、以下のサービスの領収書をアップロードしてください。\n\n{missing_services}\n\nアップロードページ: {upload_url}\n\nアップロード後は、対象領収書月の領収書が揃っていることを確認して「提出する」を押してください。\n\n{app_name}', verbose_name='通常リマインダー本文'),
        ),
        migrations.AlterField(
            model_name='emailreminderschedule',
            name='initial_subject_template',
            field=models.CharField(default='{app_name}: {receipt_month}分の領収書アップロードをお願いします', max_length=255, verbose_name='通常リマインダー件名'),
        ),
        migrations.AlterField(
            model_name='emailreminderschedule',
            name='urgent_body_template',
            field=models.TextField(default='{user_name} 様\n\nまだ領収書をアップロードしていない方にお送りします。\n提出月 {target_month} の対象となる {receipt_month}分の確認が完了していません。本日中にご対応ください。\n\n未アップロードのサービス:\n{missing_services}\n\n従量課金 / APIの利用確認が必要なサービス:\n{api_pending_services}\n\nAPIサービスを利用していない場合は、アップロードページで「対象領収書月は利用なし」を選択してください。\n\nアップロードページ: {upload_url}\n\n{app_name}', verbose_name='重要リマインダー本文'),
        ),
        migrations.AlterField(
            model_name='emailreminderschedule',
            name='urgent_subject_template',
            field=models.CharField(default='【重要】{app_name}: {receipt_month}分の領収書を本日中にアップロードしてください', max_length=255, verbose_name='重要リマインダー件名'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ai_check_period_match',
            field=models.BooleanField(default=False, verbose_name='AI確認: 対象領収書月一致'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ai_period_check_memo',
            field=models.TextField(blank=True, verbose_name='AI対象領収書月確認メモ'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ai_period_check_status',
            field=models.CharField(choices=[('not_checked', '未確認'), ('matched', '対象領収書月確認済み'), ('mismatched', '対象領収書月不一致'), ('unknown', '確認不可')], default='not_checked', max_length=20, verbose_name='AI対象領収書月確認ステータス'),
        ),
        migrations.RunPython(
            apply_submission_receipt_month_semantics,
            reverse_submission_receipt_month_semantics,
        ),
    ]
