# Generated by Django 5.2.16 on 2026-07-21

from datetime import date

from django.db import migrations, models


RECONCILE_MARKER = "【月次ルール更新】明細月と対象領収書月の対応を修正したため、最新の領収書と再照合します。"
ITEM_RECONCILE_NOTE = "旧月次ルールで照合された領収書を解除しました。"


def _month_start(value):
    return value.replace(day=1)


def _next_month(value):
    value = _month_start(value)
    if value.month == 12:
        return date(value.year + 1, 1, 1)
    return date(value.year, value.month + 1, 1)


def _parse_month(value):
    value = (value or "").strip()
    if len(value) != 7:
        return None
    try:
        return date.fromisoformat(f"{value}-01")
    except ValueError:
        return None


def _append_once(current, addition, *, limit=None):
    current = (current or "").strip()
    if addition in current:
        result = current
    else:
        result = " ".join(part for part in (current, addition) if part)
    return result[:limit] if limit else result


def apply_card_statement_month_semantics(apps, schema_editor):
    """既存明細を「明細月 = 提出月 / 対象領収書月 = 前月」へ安全に補正する。"""

    CardStatement = apps.get_model("receipts", "CardStatement")
    CardStatementItem = apps.get_model("receipts", "CardStatementItem")

    # 旧画面では period_month を「領収書月」と表示していたため、前月を選択して
    # アップロードされた記録があり得る。AI判定明細月がちょうど翌月なら、
    # period_month を本来の明細月へ移す。
    for statement in CardStatement.objects.all().iterator(chunk_size=200):
        corrected_period = _month_start(statement.period_month)
        parsed_period = _parse_month(statement.statement_period)
        if parsed_period and parsed_period == _next_month(corrected_period):
            corrected_period = parsed_period
            CardStatement.objects.filter(pk=statement.pk).update(period_month=corrected_period)

        if statement.status in {"processing", "failed"}:
            continue

        items = CardStatementItem.objects.filter(statement_id=statement.pk).select_related(
            "matched_receipt__submission"
        )
        if not items.exists():
            continue

        # 旧実装は明細月の翌月提出を見ていたため、正しい提出月ではない領収書との
        # 自動照合だけ解除する。管理者が確定したユーザー・サービス指定は保持し、
        # v1.5.4の画面表示時に保存済み明細行を正しい月で一度だけ再照合する。
        for item in items.iterator(chunk_size=500):
            receipt = item.matched_receipt
            if not receipt or not receipt.submission_id:
                continue
            receipt_submission_month = _month_start(receipt.submission.period_month)
            if receipt_submission_month == corrected_period:
                continue

            manual_override = item.match_confidence >= 1.0 and (item.match_memo or "").startswith("管理者")
            item.matched_receipt_id = None
            update_fields = ["matched_receipt"]
            if not manual_override:
                item.matched_user_id = None
                item.matched_service_id = None
                update_fields.extend(["matched_user", "matched_service"])
                if item.match_status == "matched":
                    item.match_status = "ambiguous"
                    update_fields.append("match_status")
            item.match_memo = _append_once(item.match_memo, ITEM_RECONCILE_NOTE)
            update_fields.append("match_memo")
            item.save(update_fields=update_fields)

        CardStatement.objects.filter(pk=statement.pk).update(
            status="needs_review",
            reconciled_at=None,
            ai_admin_memo=_append_once(statement.ai_admin_memo, RECONCILE_MARKER, limit=5000),
        )


def reverse_card_statement_month_semantics(apps, schema_editor):
    # 月補正と照合解除を安全に元へ戻せないため、逆移行では何もしない。
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0020_submission_receipt_month_semantics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardstatement",
            name="period_month",
            field=models.DateField(verbose_name="明細月"),
        ),
        migrations.AlterField(
            model_name="cardstatement",
            name="statement_period",
            field=models.CharField(blank=True, max_length=7, verbose_name="AI判定明細月"),
        ),
        migrations.RunPython(
            apply_card_statement_month_semantics,
            reverse_card_statement_month_semantics,
        ),
    ]
