# Generated by Django 5.2.16 on 2026-07-21 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0021_card_statement_month_semantics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStatementMatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='候補順位')),
                ('score', models.IntegerField(default=0, verbose_name='照合スコア')),
                ('confidence', models.FloatField(default=0, verbose_name='候補信頼度')),
                ('strength', models.CharField(choices=[('strong', '強い候補'), ('amount_only', '金額候補'), ('possible', '参考候補')], default='possible', max_length=20, verbose_name='候補種別')),
                ('amount_match', models.BooleanField(default=False, verbose_name='金額一致')),
                ('amount_match_basis', models.CharField(blank=True, max_length=20, verbose_name='金額一致基準')),
                ('currency_match', models.BooleanField(default=False, verbose_name='通貨一致')),
                ('merchant_match', models.BooleanField(default=False, verbose_name='ご利用先・払先関連')),
                ('service_match', models.BooleanField(default=False, verbose_name='サービス関連')),
                ('date_match', models.BooleanField(default=False, verbose_name='日付一致・近接')),
                ('rationale', models.TextField(blank=True, verbose_name='候補理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='receipts.cardstatementitem', verbose_name='明細行')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_match_candidates', to='receipts.receipt', verbose_name='候補領収書')),
            ],
            options={
                'verbose_name': 'カード明細照合候補',
                'verbose_name_plural': 'カード明細照合候補',
                'ordering': ['item', 'rank', '-score', 'receipt'],
                'indexes': [models.Index(fields=['item', 'rank'], name='receipts_ca_item_id_05a75b_idx'), models.Index(fields=['receipt', 'score'], name='receipts_ca_receipt_deb06a_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'receipt'), name='unique_statement_item_receipt_candidate'), models.UniqueConstraint(fields=('item', 'rank'), name='unique_statement_item_candidate_rank')],
            },
        ),
    ]
